name: Automated Tagging

on:
  push:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v3.17.1
      with:
        github-token: ${{ secrets.github_token }}
        skip-commit: 'false'
        skip-on-empty: 'false'
        skip-version-file: 'true'
        tag-prefix: 'v'
        git-message: 'chore(release): 🔖 {version}'