name: Automated Tagging

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v3.17.1
      with:
        github-token: ${{ secrets.github_token }}
        skip-commit: "true"
        skip-on-empty: 'false'
        tag-prefix: 'v'